version: '3.8'

services:

  postgres-db:
    container_name: postgres-db
    hostname: postgres-db
    image: postgres:12-alpine3.15
    ports:
      - 5432:5432
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
    restart: always
    command: ["postgres", "-c", "max_connections=1000"]
    environment:
      POSTGRES_PASSWORD: rootpassword

volumes:
  db-data:
