spring:
  flyway:
    enabled: true
    cleanDisabled: false
    baseline-on-migrate: true
    user: postgres
    password: rootpassword
    schemas: public
  datasource:
    url: jdbc:postgresql://localhost:5432/hibernate_test_db?sslmode=disable&useUnicode=yes&characterEncoding=UTF-8&reWriteBatchedInserts=true&stringtype=unspecified
    username: postgres
    password: rootpassword
    hikari:
      connection-timeout: 20000 # maximum number of milliseconds that a client will wait for a connection
      minimum-idle: 10 # minimum number of idle connections maintained by HikariCP in a connection pool
      maximum-pool-size: 64 # maximum pool size
      idle-timeout: 10000 # maximum idle time for connection
      max-lifetime: 1000 # maximum lifetime in milliseconds of a connection in the pool after it is closed.
      auto-commit: true # default auto-commit behavior.
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
